# permissions for end users to view awsvmschedulerstartsds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmschedulerstartsd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator
    app.kubernetes.io/part-of: vm-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: awsvmschedulerstartsd-viewer-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulerstartsds/status
  verbs:
  - get
