# permissions for end users to view azurevmschedulerstartsds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azurevmschedulerstartsd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator
    app.kubernetes.io/part-of: vm-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: azurevmschedulerstartsd-viewer-role
rules:
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstartsds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulerstartsds/status
  verbs:
  - get
