# permissions for end users to edit gcpvmschedulerstartsds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gcpvmschedulerstartsd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator
    app.kubernetes.io/part-of: vm-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: gcpvmschedulerstartsd-editor-role
rules:
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartsds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulerstartsds/status
  verbs:
  - get
