//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsd) DeepCopyInto(out *AWSVMSchedulerStartsd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsd.
func (in *AWSVMSchedulerStartsd) DeepCopy() *AWSVMSchedulerStartsd {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdList) DeepCopyInto(out *AWSVMSchedulerStartsdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStartsd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdList.
func (in *AWSVMSchedulerStartsdList) DeepCopy() *AWSVMSchedulerStartsdList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStartsdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdSpec) DeepCopyInto(out *AWSVMSchedulerStartsdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdSpec.
func (in *AWSVMSchedulerStartsdSpec) DeepCopy() *AWSVMSchedulerStartsdSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStartsdStatus) DeepCopyInto(out *AWSVMSchedulerStartsdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStartsdStatus.
func (in *AWSVMSchedulerStartsdStatus) DeepCopy() *AWSVMSchedulerStartsdStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStartsdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsd) DeepCopyInto(out *AWSVMSchedulerStopsd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsd.
func (in *AWSVMSchedulerStopsd) DeepCopy() *AWSVMSchedulerStopsd {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdList) DeepCopyInto(out *AWSVMSchedulerStopsdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AWSVMSchedulerStopsd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdList.
func (in *AWSVMSchedulerStopsdList) DeepCopy() *AWSVMSchedulerStopsdList {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AWSVMSchedulerStopsdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdSpec) DeepCopyInto(out *AWSVMSchedulerStopsdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdSpec.
func (in *AWSVMSchedulerStopsdSpec) DeepCopy() *AWSVMSchedulerStopsdSpec {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSVMSchedulerStopsdStatus) DeepCopyInto(out *AWSVMSchedulerStopsdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSVMSchedulerStopsdStatus.
func (in *AWSVMSchedulerStopsdStatus) DeepCopy() *AWSVMSchedulerStopsdStatus {
	if in == nil {
		return nil
	}
	out := new(AWSVMSchedulerStopsdStatus)
	in.DeepCopyInto(out)
	return out
}
