//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsd) DeepCopyInto(out *GCPVMSchedulerStartsd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsd.
func (in *GCPVMSchedulerStartsd) DeepCopy() *GCPVMSchedulerStartsd {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdList) DeepCopyInto(out *GCPVMSchedulerStartsdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStartsd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdList.
func (in *GCPVMSchedulerStartsdList) DeepCopy() *GCPVMSchedulerStartsdList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStartsdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdSpec) DeepCopyInto(out *GCPVMSchedulerStartsdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdSpec.
func (in *GCPVMSchedulerStartsdSpec) DeepCopy() *GCPVMSchedulerStartsdSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStartsdStatus) DeepCopyInto(out *GCPVMSchedulerStartsdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStartsdStatus.
func (in *GCPVMSchedulerStartsdStatus) DeepCopy() *GCPVMSchedulerStartsdStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStartsdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsd) DeepCopyInto(out *GCPVMSchedulerStopsd) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsd.
func (in *GCPVMSchedulerStopsd) DeepCopy() *GCPVMSchedulerStopsd {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsd) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdList) DeepCopyInto(out *GCPVMSchedulerStopsdList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GCPVMSchedulerStopsd, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdList.
func (in *GCPVMSchedulerStopsdList) DeepCopy() *GCPVMSchedulerStopsdList {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GCPVMSchedulerStopsdList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdSpec) DeepCopyInto(out *GCPVMSchedulerStopsdSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdSpec.
func (in *GCPVMSchedulerStopsdSpec) DeepCopy() *GCPVMSchedulerStopsdSpec {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPVMSchedulerStopsdStatus) DeepCopyInto(out *GCPVMSchedulerStopsdStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPVMSchedulerStopsdStatus.
func (in *GCPVMSchedulerStopsdStatus) DeepCopy() *GCPVMSchedulerStopsdStatus {
	if in == nil {
		return nil
	}
	out := new(GCPVMSchedulerStopsdStatus)
	in.DeepCopyInto(out)
	return out
}
